### ISSUE TITLE
背景の色の不透明度を0にしてプレビューすると歌詞テロップが何十にも重なる

### ISSUE THREAD

**Issue by Jackhappen** [shinta0806/NicoKaraMaker3#106]
背景素材→背景色のタブで、背景の色の不透明度を0に(無圧縮AVIを透過ファイルとして書き出しする為に)
しますと、

プレブビュー画面で歌詞テロップが消えるべき時に消えず 
重なったままで正常に表示されなくなります。

また、無圧縮AVIと、ffmpegoutからのUt Videoが書き出し可能になった場合、
音声なしで書き出しができたら有難いです。

何卒よろしくお願い申し上げます。

**Comment by shinta0806** [comment]
［対応状況］完了
［報告経路］コンタクト

**Comment by shinta0806** [comment]
ご報告ありがとうございます。
プレビュー時の不具合について検討したいと思います。

一方で、プレビューが治ったとしても、最終的に無圧縮 AVI で出力すると透過しません。

目的は出力したものを別の動画編集ソフトに取り込んで字幕を重ねたいということかと思いますが、その場合、出力形式を「連番 PNG（字幕のみを透過で）」にすることをお薦めします。この場合、背景色の不透明度は 100 で構いませんので、プレビューも問題無く行えます。

多くの動画編集ソフトでは、連番画像を動画のように扱う機能があるかと思います。

**Comment by Jackhappen** [comment]
ご返信誠にありがとうございます。

お返事が遅れて申し訳ございません。

了承をいたしました。

取り急ぎ、お礼までです。

**Comment by shinta0806** [comment]
Ver 10.56 にて対応完了しました。
