### ISSUE TITLE
歌詞の色を変更すると、常に最上部に戻ってしまいます

### ISSUE THREAD

**Issue by mibu945** [shinta0806/NicoKaraMaker3#116]
影片で問題を説明させていただきます
version: Ver 10.22

https://github.com/shinta0806/NicoKaraMaker3/assets/8282342/9236333c-8fe8-4929-b759-72f9d83c8851

**Comment by shinta0806** [comment]
動画ありがとうございます。
事象自体は #109 と同じため、こちらはクローズします。
