### ISSUE TITLE
プレビューできない

### ISSUE THREAD

**Issue by shinta0806** [shinta0806/NicoKaraMaker3#95]
### 質問
---

プレビューパネルで動画のプレビューができません。
対応策はありますか。

［関連質問］https://github.com/shinta0806/NicoKaraMaker3/issues/104 プレビュー時に音が出ない
［関連質問］https://github.com/shinta0806/NicoKaraMaker3/issues/96 動画出力が完了しない

**Comment by shinta0806** [comment]
### 回答
---

**【対応策 1：サンプル動画で確認する】**

背景素材パネルで、素材動画をニコカラメーカー 3 のサンプルフォルダーにある「故郷」にしてから、プレビューできるか確認します。

◆故郷でプレビューできる場合
　→ 素材動画のフォーマットを変更してみてください。もしくは、次の対応策に進みます。

◆ダメな場合
　→ 次の対応策に進みます。

**【対応策 2：Windows Update の最中ではないか確認する】**

Windows の更新中（スタートメニューに「更新して再起動」表示される場合）はプレビューできないことがあります。

一度 PC を更新して再起動し、Windows の更新を完了してからプレビューします。

◆Windows Update の完了でプレビューできる場合
　→ 対応完了です。

◆ダメな場合
　→ 次の対応策に進みます。

**【対応策 3：音が出るか確認する】**

音が出ない PC 環境ではプレビューできません。

ニコカラメーカー 3 以外のアプリで動画や音声を再生し、音が出ることを確認します。

◆他のアプリで音が出る場合
　→ 次の対応策に進みます。

◆他のアプリで音が出ない場合
　→ 音が出る PC 環境を整えます。

**【対応策 4：ビデオ拡張機能をインストールする】**

ニコカラメーカー 3 が標準で読み込める素材動画の形式は、無圧縮 AVI や H.264（AVC）の MP4 など、数種類に限られます。

同じ MP4 動画でも、映像のコーデックが H.264 以外の場合（H.265 など）は、そのままでは素材動画を読み込めないため、プレビューができません。

読み込める動画の種類を増やすには、ビデオ拡張機能をインストールします。インストール方法はヘルプを参照してください。
https://shinta.coresv.com/help/NicoKaraMaker3_JPN.html#VideoExtensionInstall

◆ビデオ拡張機能のインストールでプレビューできる場合
　→ 対応完了です。

◆ダメな場合
　→ 次の対応策に進みます。

**【対応策 5：素材を背景＋音声にしてみる】**

背景素材パネルで、「背景色」を選択し、音声ファイルとして何らかの WAVE ファイルを指定してから、プレビューできるか確認します。

◆背景色＋WAVE 音声でプレビューできた場合
　→ 一度プレビューに成功すれば、その後は、動画を素材にしてもプレビューできる可能性があります。
　→ その後も動画が素材だとプレビューできない場合は、素材動画のフォーマットを変更するか、もしくは、「連番画像ファイル＋音声ファイルを素材として使用」することにより、実質的に動画を読み込めるようになります。

◆ダメな場合
　→ 次の対応策に進みます。

**【対応策 6：パフォーマンス設定を変更する】**

環境設定のパフォーマンスパネルで、

- マルチスレッドで描画する
- ハードウェアアダプタで描画する

を両方オフにします（ニコカラメーカー 3 の再起動が必要です）。

◆パフォーマンスオフでプレビューできる場合
　→ 対応完了です。

◆ダメな場合
　→ 残念ながら、現時点でこれ以上の対応策はありません。ニコカラメーカー 3 や Windows のバージョンアップをお待ちください。使用環境（PC の機種、Windows のバージョン、GPU、サウンドカードなど）とともに開発者にご連絡いただけると、今後の参考になることがあるかもしれません。

**Comment by 2819118412** [comment]
stiil can‘t preview

**Comment by shinta0806** [comment]
@2819118412 使用環境を教えてください
- PC の機種
- Windows のバージョン
- GPU
- サウンドカード、など
